### ISSUE TITLE
0.10.0 regression: native <list> use-after-free on mass child removal (signalxjs/lynx)

### ISSUE THREAD

**Issue by andtii** [signalxjs/core#275]
Adopting core **0.10.0** in signalxjs/lynx reproducibly crashes the Lynx native list. 0.7.0, 0.8.0 and 0.9.0 are all clean. Filing here rather than on lynx because the bisect isolates the change to core, with the lynx side held identical.

## Repro

signalxjs/lynx `examples/showcase`, iOS simulator (iPhone 17 Pro, iOS 26). The Home screen is a raw `<list>` with one `<list-item>` per catalog area, filtered by a search `<Input>`. Typing "dynamic" filters 10 rows → 2, i.e. a mass removal of `<list-item>` children in one pass. That crashes the app.

The interaction is scripted (`idb ui tap` + `idb ui text`), so each trial is identical; crashes counted from new reports in `~/Library/Logs/DiagnosticReports`.

## Bisect — only the core version varies

Same lynx worktree, same showcase source, same installed native app; only the `catalog:` entry for `@sigx/reactivity` + `@sigx/runtime-core` changed between runs:

| core | crashes |
|---|---|
| 0.7.0 | 0/3 |
| 0.8.0 | 0/3 |
| 0.9.0 | 0/3 |
| **0.10.0** | **3/3** |

Deterministic, not racy. (lynx has a separate known *racy* native-list layout bug, signalxjs/lynx#603 — this is not that: it's a hard crash, 3/3, and absent on 0.9.0 under the identical script.)

## Crash

`EXC_BAD_ACCESS` / `SIGBUS` — use-after-free, entirely inside Lynx's native list recycler:

```
lynx::list::ListEventManager::SendExposureEvent
lynx::list::DefaultListAdapter::OnEnqueueElement
lynx::list::ListAdapter::EnqueueElement
lynx::list::DefaultListAdapter::RecycleItemHolder
lynx::list::ListAdapter::RecycleRemovedItemHolders
lynx::list::LinearLayoutManager::HandleLayoutOrScrollResult
lynx::list::LinearLayoutManager::OnLayoutAfter
lynx::list::LinearLayoutManager::OnLayoutChildren
lynx::list::ListContainerImpl::OnLayoutChildren
lynx::tasm::ListMediator::OnLayoutChildren
lynx::tasm::ListElement::OnListElementUpdated
lynx::shell::LayoutMediator::HandleListOrComponentUpdated
```

No JS exception or sigx error precedes it on the device console — the JS side looks healthy right up to the native fault. Native dispatches an exposure event to an item holder that has already been freed during recycle-on-removal, which points at element op **ordering/lifetime** on removal rather than at any single JS API.

Note scrolling the 10k-item windowed list demo (`@sigx/lynx-list`) is fine on 0.10.0 — recycling during scroll works. It is specifically **mass removal** of `<list-item>` children that faults.

## What I ruled out

Diffing the published `src/` between 0.9.0 and 0.10.0 (thanks to core shipping `src/` since 0.8.0):

- **`renderer.ts`, `scheduler.ts`, `jsx-runtime.ts`, `component-lifecycle.ts` — no behavioral change at all.** Their only diff is the `process.env.NODE_ENV` → `__DEV__` swap (#233). So the reconcile/unmount path is byte-for-byte equivalent in behavior.
- **`@sigx/reactivity` 0.9.0 → 0.10.0 — no behavioral change.** Every diff in `effect.ts`, `signal.ts`, `computed.ts`, `devtools-hook.ts` is the same `__DEV__` swap.
- **`props-accessor.ts` `unwrapVNodeValue` (#194) — tested and ruled out.** I patched the installed 0.10.0 dist to make it the identity function (confirmed live: the served bundle shrank by 338 bytes) and it still crashed 3/3. (Filed separately as #274 for an unrelated robustness concern.)

That leaves the behavioral deltas in `di/injectable.ts` (notably `lookupProvided` → `lookupProvidedEntry` with the live root-provides read, #215), `app.ts`, `errors.ts` (#234), `error-scope.ts`, and the async/`Defer` surface. None obviously touches element removal, which is why I'm bringing it here rather than guessing further — a commit-level bisect of v0.9.0..v0.10.0 is the natural next step and is much cheaper from inside this repo.

Happy to run any candidate build against the device repro.

**Comment by andtii** [comment]
**Correction — the bisect table in the issue body is wrong. Please disregard it; I'm re-running it properly.**

Two methodology faults, both mine:

1. **The metric was unsound.** I counted new entries in `~/Library/Logs/DiagnosticReports`. But the app can die on this path **without** writing a crash report — I've now caught v0.9.0 booting fine, then vanishing to the springboard after typing, with no report generated. So "0/3 crashed" often meant "died quietly", not "healthy". The metric now distinguishes crash / died / alive-and-filtered, and verifies the app actually rendered.

2. **The lynx side wasn't held constant.** My branch carried a `declareLiveClient()` call (the fix for `useData` never firing on Lynx — core's own gate, `isLiveClient()`, is false on a windowless runtime). `declareLiveClient` only exists from #220 onward, so at every commit **below** #220 the app died at module load with `declareLiveClient is not a function` and never rendered a list. Those runs were scored "clean" when the app was simply dead. That silently invalidated every data point below #220 — including the 0.8.0 and 0.9.0 rows.

What still holds, verified by screenshot rather than by report-counting:

- **0.7.0 is genuinely healthy** — typing filters the list and the app stays alive.
- **0.10.0 genuinely dies**, 3/3, and does so **with and without** the `declareLiveClient()` call, so my fix is not the trigger.
- **0.9.0 also dies** (quietly, no crash report) — so this is **not** a 0.10.0 regression, and the "first bad commit" I was closing in on (#220 / #215) is an artifact of fault 2 above.

The real range is somewhere in **v0.7.0..v0.9.0**, not v0.9.0..v0.10.0. The native stack, the repro, and the use-after-free in `RecycleRemovedItemHolders` → `SendExposureEvent` on mass `<list-item>` removal all stand as reported. I'll post a corrected bisect once it's re-run against the fixed harness, and I won't quote numbers again until each point is screenshot-verified.

Apologies for the noise — better to correct it than leave a wrong bisect standing.

**Comment by andtii** [comment]
Android confirmation + root cause — this is lynx's bug, not core's. Closing the loop from the signalxjs/lynx side:

- **Reproduced on Android** (Pixel 9 Pro XL and emulator, release build): same repro (typing in the showcase Home search → mass `<list-item>` removal), SIGSEGV in liblynx.so, and the fault is the same recycler path your stack shows (`RecycleRemovedItemHolders → OnEnqueueElement → SendExposureEvent`).
- **Root cause**: `listRemoveChild` in lynx's `packages/lynx-runtime-main/src/list-mt.ts` tore down bound snapshot cells at REMOVE-op time; native only learns of removals from the next `update-list-info` diff and touches the outgoing cell while reconciling it → use-after-free. Core version was never the variable (consistent with your retraction — the lynx repo pins core 0.7.x and crashes identically).
- **Why it looked version-correlated**: only the snapshot list path has this ordering; the legacy op path pins engine references and doesn't crash (snapshots became the lynx default recently, muddying A/Bs whose lynx side wasn't held constant).
- **Fix**: signalxjs/lynx#653 (tracking issue signalxjs/lynx#652) — removed-but-bound cells stay fully wired as zombies until native releases their holders via `enqueueComponent`, then detach/pool/destroy. Device-verified: the previously 100%-fatal filter gauntlet survives; ops-layer regression tests added.

Suggest closing this once lynx#653 merges — happy to have it transferred to signalxjs/lynx instead if you prefer to keep the history.

**Comment by andtii** [comment]
**Closing — misattributed. This was a bug in signalxjs/lynx, not in core.**

The use-after-free was in lynx's main-thread renderer: it tore down / detached a `<list-item>`'s bound cell at REMOVE time, while the native recycler still held the holder and could dispatch an exposure event to it (hence the `ListEventManager::SendExposureEvent ← RecycleRemovedItemHolders` stack). Fixed in signalxjs/lynx#653 — "defer list cell teardown until native releases the holder" (zombie-defer to `enqueueComponent`).

Core 0.10.0's element/event-lifecycle changes made the pre-existing lynx bug reliably reproducible, which is what sent me looking here, but the defect and the fix are both on the lynx side. Apologies for the noise and the earlier bad bisect table. Core is exonerated. #274 (the `isVNodeLike` structural-sniff robustness note) stands on its own and is unaffected by this.
